### ISSUE TITLE
Renew SSL Cert

### ISSUE THREAD

**Issue by RodzynDev** [Upinel/localhost.direct#1]
Hello!

I would like to ask you to renew SSL certificate ;) 

![image](https://user-images.githubusercontent.com/8007866/75235495-9f854180-57bc-11ea-83b5-7af123354c09.png)

**Comment by Upinel** [comment]
Thanks for your support! Cert updated!
Happy coding!

**Comment by RodzynDev** [comment]
The year has gone, we need to again renew SSL certificate pls ;)

**Comment by Upinel** [comment]
Thanks for your support! Cert updated! Cheers~
