### ISSUE TITLE
Invalid Chain

### ISSUE THREAD

**Issue by sfozz** [Upinel/localhost.direct#10]
it looks like the supplied chain is invalid in the most recent file. It's fine in a browser, but via `curl` (for example) I get a validation error

checking each of the certs in the bundle you can see the the intermediate supplied is incorrect.

```
➜  Downloads   openssl x509 -in 1.crt -noout -subject -issuer
subject=CN = *.localhost.direct
issuer=C = BE, O = GlobalSign nv-sa, CN = AlphaSSL CA - SHA256 - G4
➜  Downloads   openssl x509 -in 2.crt -noout -subject -issuer
subject=C = BE, O = GlobalSign nv-sa, CN = AlphaSSL CA - SHA256 - G2
issuer=C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
```

**Comment by Upinel** [comment]
Thanks for report, I've updated the Intermediate chain, it should take a few hours for CDN refresh. Thanks!
