### ISSUE TITLE
Why password-protect zip?

### ISSUE THREAD

**Issue by pataquets** [Upinel/localhost.direct#11]
First, congratulations on the cool/simple/elegant idea and thank you very much for sharing it!
Just wondering, why is the certs zip file password protected?
I'm using it on a Dockerfile and, although it's no big deal, it adds an extra step.

**Comment by Upinel** [comment]
It needs to be password protected, otherwise, when Google find it without password protected it will be considered a private key leak, resulting in the cert auto revoke.

**Comment by pataquets** [comment]
Thank you @Upinel!
