### ISSUE TITLE
Why download link redirects?

### ISSUE THREAD

**Issue by Dimava** [Upinel/localhost.direct#12]
Download link redirects 
```
https://get.localhost.direct/ -> https://github.com/Upinel/localhost.direct -> https://aka.re/localhost -> https://get.localhost.direct/localhost.zip
```
What's the point of those?

**Comment by Upinel** [comment]
The primary hub for our project is on GitHub, serving as the central "homepage" where instructions can be easily updated and shared within the GitHub ecosystem. The get.localhost.direct merely functions as a hello page, redirecting users to the GitHub page for comprehensive information.

Regarding aka.re/localhost, it serves a dual purpose.
Firstly, it adds an extra layer to mitigate the risk of a Certificate Authority (CA) detecting a potential leakage of the private key in the "public" domain. (Although I doubt it really doing anything lol)
Secondly, which is the main reason, it helps avoid unexpected browser/ISP caching issues during SSL renewal. For instance, redirecting aka.re/localhost to localhost-2024.zip can be useful during urgent SSL certificate replacement or renewal.

If users are considering automation scripts, I recommend downloading the certificate via aka.re/localhost to ensure they always have the latest version.

aka.re is also my personal site.

Hope this clarifies the functionality! If you have further questions, feel free to ask.
