### ISSUE TITLE
Certificate expires in <1 month, `README.md` says already expired

### ISSUE THREAD

**Issue by rjhuijsman** [Upinel/localhost.direct#13]
Hi @Upinel !

Thank you for this project, I find it very useful in local development of SSL endpoints.

The current `README.md` suggests that the certificate being distributed has already expired:
> 2023-Jun-15 SSL Intermediate Chain update, Expire 31 Mar 2024

Fortunately it seems like the actual certificate I just downloaded will expire on May 5th. Still, that's pretty soon.

Any chance you can produce a fresh certificate for us? 🙏🏻

**Comment by Upinel** [comment]
Hi @rjhuijsman , Yes, I always shorten the expiry date on the description to let people have some more buffer :)
The 2024 renewal is done, you may download the latest one now :)
Thanks~~~
