### ISSUE TITLE
'Unknown Issuer' error with curl & wget

### ISSUE THREAD

**Issue by mundry** [Upinel/localhost.direct#14]
Hi,

thank you for this brilliant offer.

According to my own testing, it looks like the intermediate certificate [GlobalSign GCC R6 AlphaSSL CA 2023](https://support.globalsign.com/ca-certificates/intermediate-certificates/alphassl-intermediate-certificates#globalsign-gcc-r6-alphassl-ca-2023) of the latest version of *.localhost.direct is not part of the default CA bundle on neither Fedora 39, Ubuntu 24.04, nor Arch Linux.

This results in connections not being trusted by command line tools, like `curl` and `wget`.

The intermediate certificate is also not part of the bundle offered by curl [here](https://curl.se/docs/caextract.html).

The current version of the certificate works fine in Firefox and current Chromium-based browsers.

There were also no issues with the previous version of the certificate.

```
# openssl s_client -connect cms.localhost.direct:443
CONNECTED(00000003)
depth=0 CN = *.localhost.direct
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.localhost.direct
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = *.localhost.direct
verify return:1
---
Certificate chain
 0 s:CN = *.localhost.direct
   i:C = BE, O = GlobalSign nv-sa, CN = GlobalSign GCC R6 AlphaSSL CA 2023
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Apr 17 19:19:39 2024 GMT; NotAfter: May 19 19:19:38 2025 GMT
 1 s:C = BE, O = GlobalSign nv-sa, CN = AlphaSSL CA - SHA256 - G4
   i:C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Oct 12 03:49:43 2022 GMT; NotAfter: Oct 12 00:00:00 2027 GMT
---
```

```
# curl -v https://cms.localhost.direct
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

```
# wget https://cms.localhost.direct
--2024-04-20 17:16:35--  https://cms.localhost.direct/
Resolving cms.localhost.direct (cms.localhost.direct)... 192.168.178.107
Connecting to cms.localhost.direct (cms.localhost.direct)|192.168.178.107|:443... connected.
ERROR: cannot verify cms.localhost.direct's certificate, issued by 'CN=GlobalSign GCC R6 AlphaSSL CA 2023,O=GlobalSign nv-sa,C=BE':
  Unable to locally verify the issuer's authority.
To connect to cms.localhost.direct insecurely, use `--no-check-certificate'.
```

Adding the intermediate certificate linked above to the local CA bundle resolves the issue.

I'm not sure what you can do about it on your end, except for issuing a new certificate with a different chain. Nonetheless, I thought I'd bring this to your attention.

**Comment by Upinel** [comment]
It works without issue on my side.
<img width="595" alt="Screenshot 2024-04-20 at 18 45 00" src="https://github.com/Upinel/localhost.direct/assets/2548659/d7582bc5-178e-4ee3-affc-3b609cb1ede4">

**Comment by mundry** [comment]
Like I said, there is no issue in browsers. It's just command line tools using the CA bundle from system's ca-certificates package installation.

**Comment by Upinel** [comment]
hmmm, that's interesting, I believe it is about the GlobalSign R6 Intermediate Certificates (19/07/2023) is too new, I think?

**Comment by Upinel** [comment]
But it really make no sense when the root CA cert (GlobalSign) is actually from 10/12/2014, the trust chain should works...

**Comment by Upinel** [comment]
Just tested my curl (on my Mac), it works.
<img width="3120" alt="Screenshot 2024-04-20 at 19 01 05" src="https://github.com/Upinel/localhost.direct/assets/2548659/800e8eab-ad39-4bac-a88f-f6bd26d15501">

**Comment by Upinel** [comment]
let me boot a Debian testbed for further testing

**Comment by Upinel** [comment]
I've just updated the cert with a longer trust chain with cross trusting GlobalSign GCC R6 AlphaSSL CA 2023, GlobalSign Root CA - R6 and GlobalSign Root CA, it could solve the issue.

**Comment by mundry** [comment]
Yup, it looks good, now.

```
# openssl s_client -connect cms.localhost.direct:443
CONNECTED(00000003)
depth=2 OU = GlobalSign Root CA - R6, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign GCC R6 AlphaSSL CA 2023
verify return:1
depth=0 CN = *.localhost.direct
verify return:1
---
Certificate chain
 0 s:CN = *.localhost.direct
   i:C = BE, O = GlobalSign nv-sa, CN = GlobalSign GCC R6 AlphaSSL CA 2023
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Apr 17 19:19:39 2024 GMT; NotAfter: May 19 19:19:38 2025 GMT
 1 s:C = BE, O = GlobalSign nv-sa, CN = GlobalSign GCC R6 AlphaSSL CA 2023
   i:OU = GlobalSign Root CA - R6, O = GlobalSign, CN = GlobalSign
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jul 19 03:43:25 2023 GMT; NotAfter: Jul 19 00:00:00 2026 GMT
 2 s:OU = GlobalSign Root CA - R6, O = GlobalSign, CN = GlobalSign
   i:C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA384
   v:NotBefore: Jun 19 00:00:00 2019 GMT; NotAfter: Jan 28 12:00:00 2028 GMT
---
```

Thank you, much appreciated!

**Comment by Upinel** [comment]
Just a short note as record, the AlphaSSL CA - SHA256 - G2 became invalid at the end of 2022 and was replaced by AlphaSSL CA - SHA256 - G4, which points to the GlobalSign Root CA. However, after January 28, 2024, the certificate issuance was taken over by GlobalSign GCC R6 AlphaSSL CA 2023 with a trust anchor leading to GlobalSign Root CA - R6. We've rebuild the certificate chain by appending the detailed block of code after the leaf certificate, thus ensuring compatibility by linking to the older and more widely accepted root certificate.
Case closed.
