### ISSUE TITLE
proxy_pass with nginx

### ISSUE THREAD

**Issue by anselal** [Upinel/localhost.direct#4]
Hi there,

does SSL only work with port :443 ?

I tried to proxypass a subdomain eg. anselal.localhost.direct to localhost:3005 and it didn't work...

Not sure if this is possible with this project.

**Comment by Upinel** [comment]
It should work with any ports.
*.localhost.direct will always point to 127.0.0.1, so anselal.localhost.direct:3005 will point to localhost:3005, if you proxy the *:443 to *:3005, it should work right away

**Comment by anselal** [comment]
I was trying something else before but this is how it finally works for me:

```md
    server {
        listen       443 ssl;
        server_name  anselal.localhost.direct;

        ssl_certificate      localhost.direct.crt;
        ssl_certificate_key  localhost.direct.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
		proxy_pass http://localhost:3005;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
```
