### ISSUE TITLE
Replicate this

### ISSUE THREAD

**Issue by cagnulein** [Upinel/localhost.direct#8]
Hi, I would like to replicate this in order to have a backup in case you will think to stop this :)
Did you follow a tutorial? Which provider did you use?
Thanks

**Comment by whiler** [comment]
it seems that the domain `localhost.direct` is registered at http://domains.google.com  and https://www.cloudflare.com/ provides the DNS service, and https://www.alphassl.com/ provides the signed certificate.

using these providers, maybe, you can replicate this with an new domain.

**Comment by cagnulein** [comment]
thanks @whiler
