### ISSUE TITLE
Alternative Support

### ISSUE THREAD

**Issue by cagnulein** [Upinel/localhost.direct#9]
@Upinel do you have other ways to support? Because paypal wants 4€ as a fee, I think it's insane! Let me know
I would like to send you some coffes for your hard work!

**Comment by Upinel** [comment]
I have Revolut tag @upinel and
IBAN GB93SRLG60837116754512
BIC SRLGGB2L
Cheers <3

**Comment by cagnulein** [comment]
I will send you some coffees by IBAN! Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 10 mar 2023 alle ore 15:47 Upinel ***@***.***>
ha scritto:

**Comment by Upinel** [comment]
love u <3

**Comment by cagnulein** [comment]
@Upinel at the end i created a revolut account and i sent some money there!

i hope you will keep this alive as soon as possible!
